import React from 'react';
import { LessonProject } from '../types';
import { Download, LayoutList, FileJson } from 'lucide-react';

interface BuilderPanelProps {
  project: LessonProject;
}

export const BuilderPanel: React.FC<BuilderPanelProps> = ({ project }) => {
  const handleDownload = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(project, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `lesson-${project.id}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm h-full flex flex-col">
      <div className="bg-slate-50 border-b border-slate-200 p-4 flex justify-between items-center">
        <div className="flex items-center gap-2 text-slate-700">
          <LayoutList className="w-5 h-5" />
          <h3 className="font-bold">Lesson Blueprint</h3>
        </div>
        <button 
          onClick={handleDownload}
          className="text-sm bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-3 py-1.5 rounded-md flex items-center gap-2 transition-colors"
        >
          <Download className="w-4 h-4" />
          Export JSON
        </button>
      </div>

      <div className="p-6 overflow-y-auto flex-1 space-y-8">
        <div>
           <h2 className="text-xl font-bold text-slate-900">{project.videoTitle}</h2>
           <p className="text-slate-500 mt-1">{project.videoDescription.substring(0, 150)}...</p>
           <div className="flex gap-2 mt-4">
             <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded-md uppercase font-bold">{project.audience}</span>
             <span className="px-2 py-1 bg-purple-100 text-purple-700 text-xs rounded-md uppercase font-bold">{project.difficulty}</span>
           </div>
        </div>

        <div className="space-y-6">
          {project.levels.map((level, i) => (
            <div key={level.id} className="border border-slate-200 rounded-lg p-4 relative group hover:border-arcade-300 transition-colors">
              <div className="absolute top-4 right-4 text-xs font-mono text-slate-400">
                Lvl {i + 1}
              </div>
              <h4 className="font-bold text-slate-800 text-lg mb-1">{level.title}</h4>
              <p className="text-sm text-slate-600 mb-4">{level.description}</p>
              
              <div className="space-y-3 pl-4 border-l-2 border-slate-100">
                {level.questions.map((q, j) => (
                  <div key={q.id} className="text-sm">
                    <div className="flex items-center gap-2 mb-1">
                       <span className="font-bold text-arcade-600">Q{j + 1}.</span>
                       <span className="uppercase text-[10px] tracking-wider font-bold text-slate-400 border border-slate-200 px-1 rounded">
                         {q.type.replace('_', ' ')}
                       </span>
                       <span className="text-xs text-slate-400 ml-auto">{q.points} pts</span>
                    </div>
                    <p className="text-slate-700 mb-1">{q.question}</p>
                    <p className="text-slate-500 italic text-xs">Ans: {q.correctAnswer}</p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
      
      <div className="p-4 bg-slate-50 border-t border-slate-200 text-center">
         <p className="text-xs text-slate-500 flex items-center justify-center gap-2">
            <FileJson className="w-3 h-3" />
            Generated by Gemini 3 Pro
         </p>
      </div>
    </div>
  );
};
